
name: "Chocolatey CI workflow"

on:
  push:
    branches: [ master ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month


jobs:

  windows-latest-pwsh-osquery:
    name: "windows-latest Microsoft Windows Server 2019 Datacenter pwsh"  
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: "Install osquery" 
      run: choco install osquery   
    - name: "Close/reopen your shell to see the changes" 
      run: refreshenv
      shell: pwsh        
    #https://osquery.readthedocs.io/en/stable/installation/install-windows/#running-osquery      
    # - name: "Running osquery using Powershell" 
    #   run: Start-Service osqueryd
    #   shell: pwsh               
    - name: "check if server is virtual"
      run: Systeminfo | findstr /i model   
    - name: "check the PROCESSOR_ARCHITECTURE environment variable.64-bit systems will say AMD64 and 32-bit systems should say x86"
      run: wmic OS get OSArchitecture     
    - name: "osfingerprinting"
      run: systeminfo | more  
    - name: "display all processes, executable path"
      run: wmic process list full         
    - name: "list of running services"
      run: tasklist         
    - name: "list of all processes along with their corresponding PID, and services that are tied to them"
      run: tasklist /svc  
    - name: "look for unusual services"
      run: net start                       
    - name: "query unusual services"
      run: sc query 
