name: "maven CI workflow"

on:
  push:
    # branches: [ $default-branch ]
    branches: [ feature_githubactions ]
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  
  build-linux-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml

  build-windows-job:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

  build-macos-job:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8        