name: "Pylint CI workflow"


on:
  push:
    branches: [ feature_githubactions ]
  # pull_request:
  #   branches: [ githubactions_powershell ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Set up Python 3.8"
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`

  build-ubuntu-latest-job:
    name: "Python Package using Conda on ubuntu 18.04 "
    runs-on: ubuntu-latest # 18.04
    strategy:
      # max-parallel: 5
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8']
    steps:
    - uses: actions/checkout@v2
    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`