

name: "ruby CI workflow"


on:
  push:
    branches: [ feature_githubactions ]
  # pull_request:
  #   branches: [ githubactions_powershell ]


jobs:

# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-test:
    name: "Specifying the Ruby version"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Set up Ruby"
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6  # Not needed with a .ruby-version file
    - name: "Install dependencies"
      run: bundle install
    - name: "Run tests"
      run: bundle exec rake

  
  # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-test-26:
    name: "Specifying the Ruby version 2.6"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Set up Ruby"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6  # Not needed with a .ruby-version file
    - name: "Install dependencies"
      run: bundle install
    - name: "Run tests"
      run: bundle exec rake      

# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-multiple-versions:
    name: "Testing with multiple versions of Ruby"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.7.x, 2.6.x, 2.5.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: "Install dependencies"
      run: bundle install
    - name: "Run tests"
      run: bundle exec rake      

  # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-test-caching:
    name: "Specifying the Ruby version 2.6"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Set up Ruby"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6  #Not needed with a .ruby-version file
        bundler-cache: true #Caching dependencies
    - name: "Install dependencies"
      run: bundle install #Installing dependencies with Bundler
    - name: "Run tests"
      run: bundle exec rake       

  # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-caching:
    name: "Caching without setup-ruby"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3     

  # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-macos-linux:
    name: "Matrix testing your code"
    runs-on: ${{ matrix.os }}
    # runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby: [2.5, 2.6, 2.7, head, debug, jruby, jruby-head, truffleruby, truffleruby-head]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: bundle install
    - run: bundle exec rake       

  # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-macos-linux-caching:
    name: "Matrix testing your code"
    runs-on: ${{ matrix.os }}
    # runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby: [2.5, 2.6, 2.7, head, debug, jruby, jruby-head, truffleruby, truffleruby-head]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/cache@v2 #include the matrix variables in your cache key
      with:
        path: vendor/bundle
        key: bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby-version }}-        
    - run: bundle install
    - run: bundle exec rake      

  # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-macos-linux-rubocop:
    name: "Linting your code"
    runs-on: ${{ matrix.os }}
    # runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby: [2.5, 2.6, 2.7, head, debug, jruby, jruby-head, truffleruby, truffleruby-head]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: bundle install
    - name: "Rubocop"
      run: rubocop    
    - run: bundle exec rake  